name: 'build for version'
run-name: 'build for version ${{ inputs.base_version }}${{ github.event.client_payload.base_version }}'

on:
  workflow_dispatch:
    inputs:
      base_version:
        description: 'base version'
        required: true
        default: 'x.x.x'
  repository_dispatch:
    types: [build_version]

jobs:
  build_version:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set version
        run: echo "BASE_VERSION=${{ inputs.base_version }}${{ github.event.client_payload.base_version }}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE }},ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ env.BASE_VERSION }}
            type=raw,value=latest,enable=${{ github.event.client_payload.is_latest == 'yes' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          # create an alias for arm64 (TARGETARCH in build arg) from the existing aarch64 image
          # create an alias for arm (TARGETARCH in build arg) from the existing armv7 image
          build-contexts: |
            ghcr.io/ihost-open-source-project/hassio-ihost-silabs-multiprotocol-aarch64:${{ env.BASE_VERSION }}=docker-image://ghcr.io/ihost-open-source-project/hassio-ihost-silabs-multiprotocol-aarch64:${{ env.BASE_VERSION }}
            ghcr.io/ihost-open-source-project/hassio-ihost-silabs-multiprotocol-arm:${{ env.BASE_VERSION }}=docker-image://ghcr.io/ihost-open-source-project/hassio-ihost-silabs-multiprotocol-armv7:${{ env.BASE_VERSION }}
          platforms: linux/amd64,linux/aarch64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          build-args: |
            BASE_VERSION=${{ env.BASE_VERSION }}
